#include <string.h>  // memcpy
#include <stddef.h>  // offsetof

#include <rsx/rsx.h>
#include <rsx/gcm_sys.h>

#include "rsxutil.h"
#include "screen/screen.h"

// simple_vpo.h/simple_fpo.h are generated by the Makefile from
// source/screen/simple.vcg and simple.fcg. simple.fcg started as a
// verbatim copy of PSL1GHT's known-working "rsxtest" sample shader
// (diffuse_specular_shader), with only the texture sampling removed (the
// final color is now lighting-only: diffuse + globalAmbient + specular).
//
// The per-frame sequence below is ported line-for-line from the LOCAL copy
// of that sample that is verified to render on this machine
// (shader-triangle-test/rsxtest-bisect/source/main.cpp), not from a GitHub
// fork: the fork used an older PSL1GHT API and differed in several details
// (Z16 vs Z24S8 depth, depth clear value, ZMinMax args, no user-clip-plane
// disable, no texture cache invalidate/remap) that each turned out to
// matter. See CLAUDE.md's "Shader compilation (Cg / cgcomp)" section.
#include "simple_vpo.h"
#include "simple_fpo.h"

// One entry per vertex, in the exact layout the vertex shader expects.
// "normal" is needed for the shader's lighting math; "texcoord" is no
// longer used for anything (the fragment shader doesn't sample a texture
// any more -- see simple.fcg) but is kept so the vertex format still
// matches what the shader declares as input.
struct Vertex
{
	f32 pos[3];       // x, y, z in clip space (see sIdentityMatrix below)
	f32 normal[3];    // surface direction, used by the shader's lighting math
	f32 texcoord[2];  // unused -- see the comment above
};

// The on-screen display is a grid of squares, screenCols wide and
// screenRows tall (64x32 matches the classic CHIP-8 pixel display).
static const u32 screenCols = 64;
static const u32 screenRows = 32;

// Every square is drawn as 2 triangles (top-left/bottom-left/bottom-right
// and top-left/bottom-right/top-right), 3 vertices each -- so the whole
// grid needs cols * rows * 6 vertices total.
static const u32 screenVertexCount = screenCols * screenRows * 6;

// The vertex shader always does:
//   ePosition = mul(mul(projMatrix, modelViewMatrix), vertexPosition)
// An identity matrix (1s on the diagonal, 0s elsewhere) leaves a position
// completely unchanged when multiplied by it -- like multiplying a number
// by 1. Using it for both matrices means whatever coordinates we put in
// Vertex::pos are used as-is, with no camera/projection transform at all.
static const f32 sIdentityMatrix[16] = {
	1.0f, 0.0f, 0.0f, 0.0f,
	0.0f, 1.0f, 0.0f, 0.0f,
	0.0f, 0.0f, 1.0f, 0.0f,
	0.0f, 0.0f, 0.0f, 1.0f,
};

// --- Vertex shader handles ---
// rsxVertexProgramGetConst() looks up a uniform by the name it has in the
// .vcg source and gives back a handle we can pass to
// rsxSetVertexProgramParameter() every frame to feed it a value.
static const rsxVertexProgram *sVertexProgram;
static void *sVertexShaderCode;
static const rsxProgramConst *sProjMatrixConst;
static const rsxProgramConst *sModelViewMatrixConst;

// --- Fragment (pixel) shader handles ---
// Same idea as above, but for the shader that decides each pixel's color.
// Kd/Ks are the shader's own (short, Phong-lighting-standard) names for the
// diffuse and specular reflection color -- kept here so the names match
// what rsxFragmentProgramGetConst() actually looks up in the shader source.
static const rsxFragmentProgram *sFragmentProgram;
static u32 sFragmentShaderCodeOffset;
static const rsxProgramConst *sGlobalAmbientConst;
static const rsxProgramConst *sLightPositionConst;
static const rsxProgramConst *sLightColorConst;
static const rsxProgramConst *sEyePositionConst;
// Kd = "diffuse reflection coefficient": the material's matte, scattered-
// in-every-direction color -- basically what you'd call the object's plain
// color. Standard Phong-lighting-model notation; matches the shader's own
// uniform name "Kd" (see simple.fcg).
static const rsxProgramConst *sDiffuseColorConst;   // shader's "Kd"
// Ks = "specular reflection coefficient": the color/intensity of the
// shiny, mirror-like highlight (think glare on glass or polished metal),
// as opposed to the matte diffuse color above. Matches the shader's own
// uniform name "Ks" (see simple.fcg).
static const rsxProgramConst *sSpecularColorConst;  // shader's "Ks"
static const rsxProgramConst *sShininessConst;

// Where our vertex buffer ended up in RSX-addressable memory
// (rsxAddressToOffset() fills this in once, in screenInit()).
static u32 sVertexBufferOffset;

void screenInit()
{
	// --- Vertex shader: load it and look up its two matrix uniforms ---
	sVertexProgram = (const rsxVertexProgram*) simple_vpo;
	u32 vertexShaderCodeSize;
	// The vertex shader's compiled microcode can be handed to the GPU
	// straight from this host-memory pointer -- no separate RSX buffer
	// needed (unlike the fragment shader below).
	rsxVertexProgramGetUCode(sVertexProgram, &sVertexShaderCode, &vertexShaderCodeSize);

	sProjMatrixConst = rsxVertexProgramGetConst(sVertexProgram, "projMatrix");
	sModelViewMatrixConst = rsxVertexProgramGetConst(sVertexProgram, "modelViewMatrix");

	// --- Fragment shader: load it and copy its microcode into RSX memory ---
	sFragmentProgram = (const rsxFragmentProgram*) simple_fpo;
	void *fragmentShaderCodeSource;
	u32 fragmentShaderCodeSize;
	rsxFragmentProgramGetUCode(sFragmentProgram, &fragmentShaderCodeSource, &fragmentShaderCodeSize);

	// Unlike the vertex program (rsxLoadVertexProgram takes ucode straight
	// from a host pointer), the fragment program's microcode has to live
	// somewhere RSX can address by offset -- copy it into its own small
	// RSX-local buffer, the same way rsxutil.cpp does for the framebuffers.
	void *fragmentShaderCodeBuffer = rsxMemalign(64, fragmentShaderCodeSize);
	memcpy(fragmentShaderCodeBuffer, fragmentShaderCodeSource, fragmentShaderCodeSize);
	rsxAddressToOffset(fragmentShaderCodeBuffer, &sFragmentShaderCodeOffset);

	// Look up every uniform/sampler the fragment shader takes, by name, so
	// we can feed them values each frame in screenDraw().
	sGlobalAmbientConst = rsxFragmentProgramGetConst(sFragmentProgram, "globalAmbient");
	sLightPositionConst = rsxFragmentProgramGetConst(sFragmentProgram, "lightPosition");
	sLightColorConst = rsxFragmentProgramGetConst(sFragmentProgram, "lightColor");
	sEyePositionConst = rsxFragmentProgramGetConst(sFragmentProgram, "eyePosition");
	// "Kd" and "Ks" are the shader's own parameter names (Phong-lighting
	// notation for diffuse and specular reflection color, respectively) --
	// this string has to match simple.fcg exactly, so it stays "Kd"/"Ks"
	// even though the C++ variables above are named more descriptively.
	sDiffuseColorConst = rsxFragmentProgramGetConst(sFragmentProgram, "Kd");
	sSpecularColorConst = rsxFragmentProgramGetConst(sFragmentProgram, "Ks");
	sShininessConst = rsxFragmentProgramGetConst(sFragmentProgram, "shininess");

	// --- Build the grid of squares ---
	//
	// Earlier version of this code picked each cell's corners directly in
	// clip space (-1..1) using plain division (gridWidth/screenCols etc).
	// That looked uneven on screen: screenRows/screenCols (32/64) usually
	// don't divide the *actual* display resolution evenly (e.g. a 1080-tall
	// screen: 1080/32 = 33.75, not a whole number of pixels per row), so
	// when the GPU rasterizes our clip-space coordinates back into pixels,
	// different rows/columns round to different pixel counts -- some gaps
	// end up 1 pixel wider than others, which is what showed up as
	// "unequal gaps" on screen.
	//
	// Fix: do the division in whole pixels first (so every cell boundary
	// is an exact, shared integer pixel coordinate -- no rounding can
	// sneak in between neighbouring cells), and only convert to clip-space
	// floats at the very end, per corner.
	const u32 cellGapPixels = 1;  // fixed-width gap, in pixels, on every side of a square

	// One buffer big enough for every square's 6 vertices, allocated once
	// and filled in below.
	Vertex *vertexBuffer = (Vertex*) rsxMemalign(128, screenVertexCount * sizeof(Vertex));
	Vertex *nextVertex = vertexBuffer;  // write cursor into vertexBuffer

	for (u32 row = 0; row < screenRows; row++) {
		// This row's top/bottom edge, in pixels counted up from the bottom
		// of the screen (row 0 = bottom row). Using (row * height) / rows
		// -- integer division of the whole screen height -- instead of
		// row * (height / rows) means row and row+1 always share the exact
		// same boundary value, with any leftover pixels (from the height
		// not dividing evenly) absorbed into individual rows' sizes rather
		// than spread unpredictably across every gap.
		u32 rowBottomPixels = (row * display_height) / screenRows;
		u32 rowTopPixels = ((row + 1) * display_height) / screenRows;

		for (u32 col = 0; col < screenCols; col++) {
			// Same idea as the row edges above, but left-to-right.
			u32 colLeftPixels = (col * display_width) / screenCols;
			u32 colRightPixels = ((col + 1) * display_width) / screenCols;

			// Shrink the cell inward by cellGapPixels on every side --
			// this is what actually carves out the visible gap, and since
			// it's a fixed pixel count (not a fraction of the cell), the
			// gap itself always comes out exactly cellGapPixels*2 pixels
			// wide between any two neighbouring squares, no matter how
			// the cell sizes themselves rounded.
			f32 leftPixels = (f32)(colLeftPixels + cellGapPixels);
			f32 rightPixels = (f32)(colRightPixels - cellGapPixels);
			f32 bottomPixels = (f32)(rowBottomPixels + cellGapPixels);
			f32 topPixels = (f32)(rowTopPixels - cellGapPixels);

			f32 left = (leftPixels / display_width) * 2.0f - 1.0f;
			f32 right = (rightPixels / display_width) * 2.0f - 1.0f;
			f32 bottom = (bottomPixels / display_height) * 2.0f - 1.0f;
			f32 top = (topPixels / display_height) * 2.0f - 1.0f;

			// normal = (0,0,1) on every corner: "facing straight at the
			// camera", needed so the lighting shader lights the square
			// instead of leaving it dark. texcoord isn't read by the
			// shader at all anymore (no texture sampling -- see
			// simple.fcg), but the vertex format still has room for it and
			// the shader still declares the parameter, so we keep filling
			// it in.
			Vertex topLeft     = { { left,  top,    0.0f }, { 0.0f, 0.0f, 1.0f }, { 0.0f, 0.0f } };
			Vertex bottomLeft  = { { left,  bottom, 0.0f }, { 0.0f, 0.0f, 1.0f }, { 0.0f, 1.0f } };
			Vertex bottomRight = { { right, bottom, 0.0f }, { 0.0f, 0.0f, 1.0f }, { 1.0f, 1.0f } };
			Vertex topRight    = { { right, top,    0.0f }, { 0.0f, 0.0f, 1.0f }, { 1.0f, 0.0f } };

			// Two triangles, both wound counter-clockwise (matches
			// rsxSetFrontFace(GCM_FRONTFACE_CCW) in setupRenderState()).
			*nextVertex++ = topLeft;
			*nextVertex++ = bottomLeft;
			*nextVertex++ = bottomRight;
			*nextVertex++ = topLeft;
			*nextVertex++ = bottomRight;
			*nextVertex++ = topRight;
		}
	}

	rsxAddressToOffset(vertexBuffer, &sVertexBufferOffset);
}

// Sets up the viewport, depth test, and other render state that stays the
// same for the whole frame. Ported from the working sample's setDrawEnv().
static void setupRenderState()
{
	// Draw to all 4 color channels (R/G/B/A), on render target 0.
	rsxSetColorMask(gGcmContext, GCM_COLOR_MASK_B | GCM_COLOR_MASK_G | GCM_COLOR_MASK_R | GCM_COLOR_MASK_A);
	rsxSetColorMaskMrt(gGcmContext, 0);

	// The viewport maps clip-space coordinates (-1..1) onto actual pixel
	// coordinates. Note the negated height in scale[1]: RSX's clip space
	// has +Y pointing up, but the framebuffer's Y=0 is the top row, so this
	// flip is what makes "up" in our vertex data appear at the top of the
	// screen instead of the bottom.
	u16 x = 0, y = 0, w = (u16) display_width, h = (u16) display_height;
	f32 minDepth = 0.0f, maxDepth = 1.0f;
	f32 scale[4] = { w * 0.5f, h * -0.5f, (maxDepth - minDepth) * 0.5f, 0.0f };
	f32 offset[4] = { x + w * 0.5f, y + h * 0.5f, (maxDepth + minDepth) * 0.5f, 0.0f };

	rsxSetViewport(gGcmContext, x, y, w, h, minDepth, maxDepth, scale, offset);
	rsxSetScissor(gGcmContext, x, y, w, h);

	// Depth testing: lets closer squares draw over farther ones. Not
	// strictly needed since every square is at z=0, but keeping it enabled
	// matches the known-working sample this was ported from.
	rsxSetDepthTestEnable(gGcmContext, GCM_TRUE);
	rsxSetDepthFunc(gGcmContext, GCM_LESS);
	rsxSetShadeModel(gGcmContext, GCM_SHADE_MODEL_SMOOTH);
	rsxSetDepthWriteEnable(gGcmContext, 1);
	// Counter-clockwise vertex winding counts as "front facing" -- has to
	// match the winding order used when building the grid in screenInit().
	rsxSetFrontFace(gGcmContext, GCM_FRONTFACE_CCW);
}

void screenDraw()
{
	setupRenderState();

	// Wipe the framebuffer (to black) and depth/stencil buffers before
	// drawing this frame's squares.
	rsxSetClearColor(gGcmContext, 0x00000000);
	rsxSetClearDepthStencil(gGcmContext, 0xffffff00);
	rsxClearSurface(gGcmContext, GCM_CLEAR_R | GCM_CLEAR_G | GCM_CLEAR_B | GCM_CLEAR_A | GCM_CLEAR_S | GCM_CLEAR_Z);

	rsxSetZMinMaxControl(gGcmContext, GCM_FALSE, GCM_TRUE, GCM_FALSE);

	// One clip plane per render target slot (0..7) -- tells RSX the pixel
	// bounds it's allowed to draw into.
	for (u32 i = 0; i < 8; i++)
		rsxSetViewportClip(gGcmContext, i, display_width, display_height);

	// Tell the GPU where to find each vertex attribute in sVertexBuffer:
	// position, normal, and texcoord are interleaved per-vertex (see the
	// Vertex struct), so each call passes the byte offset of that field
	// plus sizeof(Vertex) as the stride to the next vertex.
	// Note: GCM_VERTEX_ATTRIB_POS/NORMAL/TEX0 are fixed hardware attribute
	// slot numbers, exactly as the working sample binds them -- not the
	// index rsxVertexProgramGetAttrib() would report back for these names.
	rsxBindVertexArrayAttrib(gGcmContext, GCM_VERTEX_ATTRIB_POS, 0, sVertexBufferOffset + offsetof(Vertex, pos), sizeof(Vertex), 3, GCM_VERTEX_DATA_TYPE_F32, GCM_LOCATION_RSX);
	rsxBindVertexArrayAttrib(gGcmContext, GCM_VERTEX_ATTRIB_NORMAL, 0, sVertexBufferOffset + offsetof(Vertex, normal), sizeof(Vertex), 3, GCM_VERTEX_DATA_TYPE_F32, GCM_LOCATION_RSX);
	rsxBindVertexArrayAttrib(gGcmContext, GCM_VERTEX_ATTRIB_TEX0, 0, sVertexBufferOffset + offsetof(Vertex, texcoord), sizeof(Vertex), 2, GCM_VERTEX_DATA_TYPE_F32, GCM_LOCATION_RSX);

	// Load the vertex shader and give it both matrices as identity (see the
	// comment on sIdentityMatrix above) -- so vertex positions pass through
	// completely unchanged.
	rsxLoadVertexProgram(gGcmContext, sVertexProgram, sVertexShaderCode);
	rsxSetVertexProgramParameter(gGcmContext, sVertexProgram, sProjMatrixConst, sIdentityMatrix);
	rsxSetVertexProgramParameter(gGcmContext, sVertexProgram, sModelViewMatrixConst, sIdentityMatrix);

	// Lighting constants for the fragment shader. The shader no longer
	// samples a texture (see simple.fcg) -- the final color comes straight
	// from diffuse + globalAmbient + specular, so these values directly
	// determine what color the squares end up.
	static const f32 white[3] = { 1.0f, 1.0f, 1.0f };
	static const f32 lightPosition[3] = { 0.0f, 0.0f, 5.0f };  // in front of every square
	static const f32 noSpecularHighlight[3] = { 0.0f, 0.0f, 0.0f };
	static const f32 shininess = 1.0f;

	rsxSetFragmentProgramParameter(gGcmContext, sFragmentProgram, sEyePositionConst, lightPosition, sFragmentShaderCodeOffset, GCM_LOCATION_RSX);
	rsxSetFragmentProgramParameter(gGcmContext, sFragmentProgram, sGlobalAmbientConst, white, sFragmentShaderCodeOffset, GCM_LOCATION_RSX);
	rsxSetFragmentProgramParameter(gGcmContext, sFragmentProgram, sLightPositionConst, lightPosition, sFragmentShaderCodeOffset, GCM_LOCATION_RSX);
	rsxSetFragmentProgramParameter(gGcmContext, sFragmentProgram, sLightColorConst, white, sFragmentShaderCodeOffset, GCM_LOCATION_RSX);
	rsxSetFragmentProgramParameter(gGcmContext, sFragmentProgram, sShininessConst, &shininess, sFragmentShaderCodeOffset, GCM_LOCATION_RSX);
	rsxSetFragmentProgramParameter(gGcmContext, sFragmentProgram, sDiffuseColorConst, white, sFragmentShaderCodeOffset, GCM_LOCATION_RSX);
	rsxSetFragmentProgramParameter(gGcmContext, sFragmentProgram, sSpecularColorConst, noSpecularHighlight, sFragmentShaderCodeOffset, GCM_LOCATION_RSX);

	rsxLoadFragmentProgramLocation(gGcmContext, sFragmentProgram, sFragmentShaderCodeOffset, GCM_LOCATION_RSX);

	// Never called before in this project. If the user clip planes default
	// to enabled with garbage plane equations, every fragment gets clipped
	// and nothing ever reaches the screen.
	rsxSetUserClipPlaneControl(gGcmContext,
		GCM_USER_CLIP_PLANE_DISABLE, GCM_USER_CLIP_PLANE_DISABLE, GCM_USER_CLIP_PLANE_DISABLE,
		GCM_USER_CLIP_PLANE_DISABLE, GCM_USER_CLIP_PLANE_DISABLE, GCM_USER_CLIP_PLANE_DISABLE);

	// One draw call for the entire grid -- all screenVertexCount vertices
	// were already laid out back-to-back in screenInit().
	rsxDrawVertexArray(gGcmContext, GCM_TYPE_TRIANGLES, 0, screenVertexCount);
}
