#include "romlist/romlist.h"

const RomEntry ROM_LIST[] = {
	{ "1-CHIP8-LOGO", "/app_home/roms/1-chip8-logo.ch8" },
	{ "15 PUZZLE ROGER IVIE ALT", "/app_home/roms/15 Puzzle [Roger Ivie] (alt).ch8" },
	{ "15 PUZZLE ROGER IVIE", "/app_home/roms/15 Puzzle [Roger Ivie].ch8" },
	{ "2-IBM-LOGO", "/app_home/roms/2-ibm-logo.ch8" },
	{ "3-CORAX", "/app_home/roms/3-corax+.ch8" },
	{ "4-FLAGS", "/app_home/roms/4-flags.ch8" },
	{ "5-QUIRKS", "/app_home/roms/5-quirks.ch8" },
	{ "6-KEYPAD", "/app_home/roms/6-keypad.ch8" },
	{ "7-BEEP", "/app_home/roms/7-beep.ch8" },
	{ "8-SCROLLING", "/app_home/roms/8-scrolling.ch8" },
	{ "ADDITION PROBLEMS PAUL C MOEWS", "/app_home/roms/Addition Problems [Paul C. Moews].ch8" },
	{ "AIRPLANE", "/app_home/roms/Airplane.ch8" },
	{ "ANIMAL RACE BRIAN ASTLE", "/app_home/roms/Animal Race [Brian Astle].ch8" },
	{ "ASTRO DODGE REVIVAL STUDIOS 2008", "/app_home/roms/Astro Dodge [Revival Studios, 2008].ch8" },
	{ "BIORHYTHM JEF WINSOR", "/app_home/roms/Biorhythm [Jef Winsor].ch8" },
	{ "BLINKY HANS CHRISTIAN EGEBERG 1991", "/app_home/roms/Blinky [Hans Christian Egeberg, 1991].ch8" },
	{ "BLINKY HANS CHRISTIAN EGEBERG ALT", "/app_home/roms/Blinky [Hans Christian Egeberg] (alt).ch8" },
	{ "BLITZ DAVID WINTER", "/app_home/roms/Blitz [David Winter].ch8" },
	{ "BOWLING GOOITZEN VAN DER WAL", "/app_home/roms/Bowling [Gooitzen van der Wal].ch8" },
	{ "BREAKOUT BRIX HACK DAVID WINTER 1997", "/app_home/roms/Breakout (Brix hack) [David Winter, 1997].ch8" },
	{ "BREAKOUT CARMELO CORTEZ 1979", "/app_home/roms/Breakout [Carmelo Cortez, 1979].ch8" },
	{ "BRICK BRIX HACK 1990", "/app_home/roms/Brick (Brix hack, 1990).ch8" },
	{ "BRIX ANDREAS GUSTAFSSON 1990", "/app_home/roms/Brix [Andreas Gustafsson, 1990].ch8" },
	{ "CAVE", "/app_home/roms/Cave.ch8" },
	{ "COIN FLIPPING CARMELO CORTEZ 1978", "/app_home/roms/Coin Flipping [Carmelo Cortez, 1978].ch8" },
	{ "CONNECT 4 DAVID WINTER", "/app_home/roms/Connect 4 [David Winter].ch8" },
	{ "CRAPS CAMERLO CORTEZ 1978", "/app_home/roms/Craps [Camerlo Cortez, 1978].ch8" },
	{ "DEFLECTION JOHN FORT", "/app_home/roms/Deflection [John Fort].ch8" },
	{ "FIGURES", "/app_home/roms/Figures.ch8" },
	{ "FILTER", "/app_home/roms/Filter.ch8" },
	{ "GUESS DAVID WINTER ALT", "/app_home/roms/Guess [David Winter] (alt).ch8" },
	{ "GUESS DAVID WINTER", "/app_home/roms/Guess [David Winter].ch8" },
	{ "HI-LO JEF WINSOR 1978", "/app_home/roms/Hi-Lo [Jef Winsor, 1978].ch8" },
	{ "HIDDEN DAVID WINTER 1996", "/app_home/roms/Hidden [David Winter, 1996].ch8" },
	{ "KALEIDOSCOPE JOSEPH WEISBECKER 1978", "/app_home/roms/Kaleidoscope [Joseph Weisbecker, 1978].ch8" },
	{ "LANDING", "/app_home/roms/Landing.ch8" },
	{ "LUNAR LANDER UDO PERNISZ 1979", "/app_home/roms/Lunar Lander (Udo Pernisz, 1979).ch8" },
	{ "MASTERMIND FOURROW ROBERT LINDLEY 1978", "/app_home/roms/Mastermind FourRow (Robert Lindley, 1978).ch8" },
	{ "MERLIN DAVID WINTER", "/app_home/roms/Merlin [David Winter].ch8" },
	{ "MISSILE DAVID WINTER", "/app_home/roms/Missile [David Winter].ch8" },
	{ "MOST DANGEROUS GAME PETER MARUHNIC", "/app_home/roms/Most Dangerous Game [Peter Maruhnic].ch8" },
	{ "NIM CARMELO CORTEZ 1978", "/app_home/roms/Nim [Carmelo Cortez, 1978].ch8" },
	{ "PADDLES", "/app_home/roms/Paddles.ch8" },
	{ "PONG 1 PLAYER", "/app_home/roms/Pong (1 player).ch8" },
	{ "PONG ALT", "/app_home/roms/Pong (alt).ch8" },
	{ "PONG 2 PONG HACK DAVID WINTER 1997", "/app_home/roms/Pong 2 (Pong hack) [David Winter, 1997].ch8" },
	{ "PONG PAUL VERVALIN 1990", "/app_home/roms/Pong [Paul Vervalin, 1990].ch8" },
	{ "PROGRAMMABLE SPACEFIGHTERS JEF WINSOR", "/app_home/roms/Programmable Spacefighters [Jef Winsor].ch8" },
	{ "PUZZLE", "/app_home/roms/Puzzle.ch8" },
	{ "REVERSI PHILIP BALTZER", "/app_home/roms/Reversi [Philip Baltzer].ch8" },
	{ "ROCKET LAUNCH JONAS LINDSTEDT", "/app_home/roms/Rocket Launch [Jonas Lindstedt].ch8" },
	{ "ROCKET LAUNCHER", "/app_home/roms/Rocket Launcher.ch8" },
	{ "ROCKET JOSEPH WEISBECKER 1978", "/app_home/roms/Rocket [Joseph Weisbecker, 1978].ch8" },
	{ "RUSH HOUR HAP 2006 ALT", "/app_home/roms/Rush Hour [Hap, 2006] (alt).ch8" },
	{ "RUSH HOUR HAP 2006", "/app_home/roms/Rush Hour [Hap, 2006].ch8" },
	{ "RUSSIAN ROULETTE CARMELO CORTEZ 1978", "/app_home/roms/Russian Roulette [Carmelo Cortez, 1978].ch8" },
	{ "SEQUENCE SHOOT JOYCE WEISBECKER", "/app_home/roms/Sequence Shoot [Joyce Weisbecker].ch8" },
	{ "SHOOTING STARS PHILIP BALTZER 1978", "/app_home/roms/Shooting Stars [Philip Baltzer, 1978].ch8" },
	{ "SLIDE JOYCE WEISBECKER", "/app_home/roms/Slide [Joyce Weisbecker].ch8" },
	{ "SOCCER", "/app_home/roms/Soccer.ch8" },
	{ "SPACE FLIGHT", "/app_home/roms/Space Flight.ch8" },
	{ "SPACE INTERCEPT JOSEPH WEISBECKER 1978", "/app_home/roms/Space Intercept [Joseph Weisbecker, 1978].ch8" },
	{ "SPACE INVADERS DAVID WINTER ALT", "/app_home/roms/Space Invaders [David Winter] (alt).ch8" },
	{ "SPACE INVADERS DAVID WINTER", "/app_home/roms/Space Invaders [David Winter].ch8" },
	{ "SPOOKY SPOT JOSEPH WEISBECKER 1978", "/app_home/roms/Spooky Spot [Joseph Weisbecker, 1978].ch8" },
	{ "SQUASH DAVID WINTER", "/app_home/roms/Squash [David Winter].ch8" },
	{ "SUBMARINE CARMELO CORTEZ 1978", "/app_home/roms/Submarine [Carmelo Cortez, 1978].ch8" },
	{ "SUM FUN JOYCE WEISBECKER", "/app_home/roms/Sum Fun [Joyce Weisbecker].ch8" },
	{ "SYZYGY ROY TREVINO 1990", "/app_home/roms/Syzygy [Roy Trevino, 1990].ch8" },
	{ "TAPEWORM JDR 1999", "/app_home/roms/Tapeworm [JDR, 1999].ch8" },
	{ "TETRIS FRAN DACHILLE 1991", "/app_home/roms/Tetris [Fran Dachille, 1991].ch8" },
	{ "TIC-TAC-TOE DAVID WINTER", "/app_home/roms/Tic-Tac-Toe [David Winter].ch8" },
	{ "TIMEBOMB", "/app_home/roms/Timebomb.ch8" },
	{ "UFO LUTZ V 1992", "/app_home/roms/UFO [Lutz V, 1992].ch8" },
	{ "VERS JMN 1991", "/app_home/roms/Vers [JMN, 1991].ch8" },
	{ "VERTICAL BRIX PAUL ROBSON 1996", "/app_home/roms/Vertical Brix [Paul Robson, 1996].ch8" },
	{ "WALL DAVID WINTER", "/app_home/roms/Wall [David Winter].ch8" },
	{ "WIPE OFF JOSEPH WEISBECKER", "/app_home/roms/Wipe Off [Joseph Weisbecker].ch8" },
	{ "WORM V4 RB-REVIVAL STUDIOS 2007", "/app_home/roms/Worm V4 [RB-Revival Studios, 2007].ch8" },
	{ "X-MIRROR", "/app_home/roms/X-Mirror.ch8" },
	{ "ZEROPONG ZEROZSHADOW 2007", "/app_home/roms/ZeroPong [zeroZshadow, 2007].ch8" },
	{ "TANK", "/app_home/roms/tank.ch8" },
	{ "TEST OPCODE", "/app_home/roms/test_opcode.ch8" },
	{ "TRON", "/app_home/roms/tron.ch8" },
};

const int ROM_COUNT = sizeof(ROM_LIST) / sizeof(ROM_LIST[0]);
